# Homework 01 - Intro

## Q1. Pandas Version
What's the version of Pandas that you installed?

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.2'

In [3]:
data_url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"
car_fuel_efficiency = pd.read_csv(data_url)
car_fuel_efficiency.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

## Q2. Records count
How many records are in the dataset?

In [4]:
len(car_fuel_efficiency)

9704

## Q3. Fuel types
How manu fuel types are presented in the dataset?

In [5]:
car_fuel_efficiency.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [6]:
len(car_fuel_efficiency["fuel_type"].unique())

2

## Q4. Missing values
How many columns in the dataset have missing values?

In [7]:
len(car_fuel_efficiency.columns[car_fuel_efficiency.isnull().any()])

4

## Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [8]:
car_fuel_efficiency[car_fuel_efficiency['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

## Q6. Median value of horsepower

### 1. find the median value of `horsepower` column in the dataset

In [9]:
horsepower_median = car_fuel_efficiency['horsepower'].median()
horsepower_median

np.float64(149.0)

### 2. Next, calculate the most frequent value of the same `horsepower` column.

In [10]:
horsepower_mode = car_fuel_efficiency['horsepower'].mode()[0]
horsepower_mode

np.float64(152.0)

### 3. Use `fillna` method to fill the missing values in `horsepower` column with the most frequent value from the previous step.

In [11]:
new_horsepower_col = car_fuel_efficiency['horsepower'].fillna(horsepower_mode)
new_horsepower_col.head()

0    159.0
1     97.0
2     78.0
3    152.0
4    140.0
Name: horsepower, dtype: float64

### 4. Now, calculate the median value of the horsepower once again.

In [12]:
new_horsepower_median = new_horsepower_col.median()
new_horsepower_median

np.float64(152.0)

### Has it changed?

In [13]:
print(f"""Median has {
    "increased" if new_horsepower_median > horsepower_median else
    "decreased" if new_horsepower_median < horsepower_median else
        "not changed"}.""")

Median has increased.


## 7. Sum of weights

### 1. Select all the cars from Asia

In [14]:
asia_cars = car_fuel_efficiency[car_fuel_efficiency['origin'] == 'Asia']
asia_cars.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

### 2. Select only columns `vehicle_weight` and `model_year`

In [15]:
asia_vehicle_weight_and_model_year = asia_cars[['vehicle_weight', 'model_year']]
asia_vehicle_weight_and_model_year.head()

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016

### 3. Select the first 7 values

In [16]:
first_seven_asia_vehicle_weight_and_model_year = asia_vehicle_weight_and_model_year.head(7)
first_seven_asia_vehicle_weight_and_model_year

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

### 4. Get the underlying NumPy array.

In [17]:
X = first_seven_asia_vehicle_weight_and_model_year.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

### 5. Compute matrix-matrix multiplication between the transpose of `X` and `X`.

In [18]:
XTX = X.T @ X
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

### 6. Invert `XTX`.

In [19]:
inverseXTX = np.linalg.inv(XTX)
inverseXTX

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

### 7. Create an array `y` with provided values.

In [20]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

### 8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`.

In [21]:
w = (inverseXTX @ X.T) @ y
w

array([0.01386421, 0.5049067 ])

### 9. What's the sunm of all the elements of the result?

In [22]:
w.sum()

np.float64(0.5187709081074026)